Add localization
pavelslauk/ShopTask pull request #12
Opened 2018-11-27 10:49 UTC by pavelslauk

2018-11-27 11:41 UTC, victor-makovsky-covergo commented on ShopTask.DataAccess/Entities/ProductEntity.cs
> -        [Required]
Зачем убрал атрибуты?

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Controllers/BaseController.cs
> +            var cookie = Request.Cookies["lang"];
Зачем ищешь существующий кук?

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Filters/CultureAttribute.cs
> +    public class CultureAttribute : FilterAttribute, IActionFilter
Лучше назвать CultureFilter - т к этот класс нигде не применяется как атрибут, а добавляется в коллекцию GlobalFilterCollection.

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Filters/CultureAttribute.cs
> +        public void OnActionExecuted(ActionExecutedContext filterContext)
На OnActionExecuted уже поздно устанавливать культуру (например, внутри action контроллера тоже могут быть обращения к файлам ресурсов). Установи ее как можно раньше, пожалуйста.

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Filters/CultureAttribute.cs
> +            string cultureName = "en";
Эта переменная не нужна, если нужную культуру не нашло, просто не надо ее выставлять - конкретно под наш проект так можно сделать, нет смысла усложнять.

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Filters/CultureAttribute.cs
> +            string[] cultures =  { "ru", "en" };
Вообще говоря, нет смысла добавлять какую-то фильтрацию по культурам, если на это не было явного запроса от заказчика. Но раз уж есть, сделай, пожалуйста, чтобы массив cultures не создавался при каждом вызове метода - не надо напрасно расходовать серверные ресурсы. Объяви, пожалуйста, это поле с квалификатором, говорящим, что оно никогда не поменятся, с момента первой инициализации.

И вместо массива используй, пожалуйста HashSet - нам нужна только операция поиска - во имя экономии серверных ресурсов.

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Filters/CultureAttribute.cs
> +            HttpCookie cultureCookie = filterContext.HttpContext.Request.Cookies["lang"];
"lang" - вынеси пожалуйста, эту строку в отдельный класс CookieKeys, чтобы не дублироваться. Можно поместить класс в папку Utils.

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Filters/CultureAttribute.cs
> +            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(cultureName);
Почитай, пожалуйста, чем отличаются CreateSpecificCulture от CreateCulture. В нашем случае достаточно последней.

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Resources/Resource.resx
> +﻿<?xml version="1.0" encoding="utf-8"?>
Назови, плиз, покороче - просто Res. И давай вынесем ресурсы в отдельный проект ShopTask.Resources.

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Models/CategoryModel.cs
> +        [Display(Name = "CategoryModelName", ResourceType = typeof(Resources.Resource))]
Используй using.

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Scripts/layout.js
> +        var selectedCulture = $(selectors.cultureSelect).val();
Можно получить значение выбранной культуры для текущего элемента, для которого срабатывает этот обработчик, не запуская поиск по селектору. Экономим ресурсы браузера пользователя.

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Scripts/layout.js
> +        window.location.href = changeCultureUrl + '?culture=' + selectedCulture;
Отправь, пожалуйста, пост запрос, чтобы сменить культуру (по конвенции GET запросы не должны ничего менять, хотя иногда и бывают исключения), после этого перезагрузи текущую страницу через js (на referrer на сервере лучше никогда не полагаться - см https://stackoverflow.com/questions/6023941/how-reliable-is-http-referer).

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Views/Categories/CategoriesPartial.cshtml
> +@Html.TextBoxFor(model => Model[newCategoryIndex].Name, new { @class = "new-category-input", placeholder = Resources.Resource.NewCategoryInputPlaceholder })
Resources.Resource - используй using, пожалуйста.

2018-11-27 11:41 UTC, victorm1710 commented on ShopTask/Views/Shared/_Layout.cshtml
> +                <option value="ru">Русский</option>
Смотри, у тебя фактически в двух местах на проекте (тут и в фильтре) задается список поддерживаемых локалей. Давай вынесем его в какой-то класс, чтобы не дублироваться.

2018-11-28 14:02 UTC, pavelslauk commented on ShopTask.DataAccess/Entities/ProductEntity.cs
> +        [RegularExpression(@"(^[1-9][0-9]*(\.[0-9]*)?)|(^0\.(([0-9]*)?[1-9]([0-9]*)?))$")]
При русской локализации спотыкается об эту регулярку, а об такую же в ProductModel - нет. В дебаге смотрел - в Price одинаковые значения в обоих случаях (думал что где-то . на , меняется, но нет).

2018-11-28 16:20 UTC, victor-makovsky-covergo commented on ShopTask.DataAccess/Entities/ProductEntity.cs
> +        [RegularExpression(@"(^[1-9][0-9]*(\.[0-9]*)?)|(^0\.(([0-9]*)?[1-9]([0-9]*)?))$")]
Погоди, здесь же не строка) Тут регулярка уже не нужна, можно использовать min/max.

2018-11-28 16:20 UTC, victorm1710 commented on ShopTask/Filters/CultureAttribute.cs
>          public void OnActionExecuting(ActionExecutingContext filterContext)
Хорошо, в идеале культуру устанавливать как можно раньше - лучше даже в http module, т к его события срабатывают раньше, чем фильтры mvc. Но это сделаем потом, если будет время.

2018-11-28 16:20 UTC, victorm1710 commented on ShopTask/Utils/CookieKeys.cs
> +        public static string cultureCookie = "lang";
лучше public const string CultureCookie (хотя бы readonly надо было указать). C большой буквы - т к это публичное поле.

2018-11-28 16:20 UTC, victorm1710 commented on ShopTask/Views/Shared/_Layout.cshtml
>          @("active-page-link")
Вроде можно @: "active-page-link"

2018-11-28 16:20 UTC, victorm1710 commented on ShopTask/Utils/Locals.cs
> +        public static readonly HashSet<string> languagesNames = new HashSet<string> { "English", "Русский" };
languagesNames - не используется?

2018-11-28 16:20 UTC, victorm1710 commented on ShopTask/Utils/Locals.cs
> +        public static readonly HashSet<string> cultures = new HashSet<string> { "en", "ru" };
cultures с большой буквы - публичное поле класса. Давай назовем класс LocalizationConfig, поле SupportedCultures (иначе при чтении кода сходу не очевидно, что за Cultures) и будем загружать список поддерживаемых культур из AppSettings.

2018-11-28 16:20 UTC, victorm1710 commented on ShopTask/Views/Shared/_Layout.cshtml
> +                    <option value="@culture">@CultureInfo.GetCultureInfo(culture).NativeName</option>
Хорошая идея, для тестового или домашнего проекта норм. Для настоящего проекта лучше хранить тайтлы языков в отдельном файле ресурсов (под разными ключами) - давай так и сделаем. Нам лучше иметь контроль над всеми отображаемыми пользователю текстами, не отдаваться на волю .net.

2018-11-29 11:33 UTC, victor-makovsky-covergo requested changes

2018-11-29 11:33 UTC, victorm1710 commented on ShopTask/Utils/LocalizationConfig.cs
> +                             .Where(key => key.StartsWith("SupportedCulture"))
Не, обычно, если надо хранить в сеттингах несколько значений, их кладут через запятую. Иначе appsettings конфиг будет очень сильно разрастаться.

2018-11-29 12:53 UTC, victor-makovsky-covergo approved these changes

2018-11-29 13:20 UTC, victor-makovsky-covergo commented on ShopTask.DataAccess/Entities/ProductEntity.cs
Зачем 2 метода: public async Task<ActionResult> CategoriesPartialAsync() и public ActionResult CategoriesPartial() ?

2018-11-29 13:20 UTC, victor-makovsky-covergo commented on ShopTask.DataAccess/Entities/ProductEntity.cs
>          [Required]
тут тоже длинноватая строка:
var categories = Mapper.Map<IEnumerable<Category>, List<CategoryModel>>(AsyncContext.Run(async () => await _categoriesRepository.GetAllAsync()));

2018-11-29 13:20 UTC, victor-makovsky-covergo commented on ShopTask.DataAccess/Entities/ProductEntity.cs
>          [Required]
[HttpPost]
        public ActionResult ChangeCulture(string culture)
        {
            Response.Cookies.Add(CreateCookie(culture));

            return Redirect(Request.UrlReferrer.AbsoluteUri);
        }      
а тут редирект остался?

2018-11-29 13:20 UTC, victorm1710 commented on ShopTask.DataAccess/Entities/ProductEntity.cs
>          [Required]
var products = (await _productsRepository.FindAsync(where: product => !filterCategoryId.HasValue || product.CategoryId == filterCategoryId, include: product => product.Category)).ToList();
Сделай, пожалуйста .ToList на новой строке, длиннова-то получилось.

2018-11-29 13:20 UTC, victorm1710 commented on ShopTask.DataAccess/Entities/ProductEntity.cs
>          [Required]
(await _categoriesRepository.FindAsync(where: category => category.Id == filterCategoryId)).FirstOrDefault(); - тут тоже

2018-11-29 13:20 UTC, victorm1710 commented on ShopTask.DataAccess/Entities/ProductEntity.cs
>          [Required]
GetCategorySelectList - не хватает суффикса Async

2018-11-29 13:20 UTC, victorm1710 commented on ShopTask.DataAccess/Entities/ProductEntity.cs
>          [Required]
Давай поместим все не наши файлы js в папку Scripts/Libs/

2018-11-29 13:20 UTC, victorm1710 commented on ShopTask.DataAccess/Entities/ProductEntity.cs
>          [Required]
Task<int> CommitAsync() - что означает возвращаемый int? Есть смысл добавлять его в интерфейс?

2018-12-05 08:11 UTC, merged